# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Markdown
tagline:          'Ohjeita Markdownin käyttöön tieteessä'
description:      'Ohjeita Markdown-merkintäkielen käyttöön tieteellisessä kirjoittamisessa'
url:              markdown.fi
baseurl:          ''

author:
  name:           'Jonne Arjoranta'

paginate:         5

# Kokoelmien permalinkit on määritelty käsin, koska
# github-pages hoitaa baseurlit hassusti. Olisi kiva
# jos niihin voisi määritellä {{ site.baseurl }}-
# muuttujan, mutta ilmeisesti sitä ei tueta config-
# tiedostossa. Korjausehdotuksia otetaan vastaan!
collections:
  tyokalut:
    output: true
    permalink: /tyokalut/:path/
  ohjeet:
    output: true
    permalink: /ohjeet/:path/

defaults:
  -
    scope:
      path: ""
      type: "tyokalut" # a collection in your site, in plural form
    values:
      layout: "tyokalu"
  -
    scope:
      path: ""
      type: "ohjeet" # a collection in your site, in plural form
    values:
      layout: "ohje"

# Custom vars
sidebar_image:
version:          

github:
        repo:           https://github.com/jaranta/md-tiede-fi
