# Dependencies
markdown:         kramdown
highlighter:      rouge

# Gems
gems: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Markdown ja tiede
tagline:          'Ohjeita Markdownin käyttöön tieteeessä'
description:      'Ohjeita Markdown-merkintäkielen käyttöön tieteellisessä kirjoittamisessa'
url:              https://github.com/gitkrax/md-tiede-fi
baseurl:          '/md-tiede-fi'

author:
  name:           'Jonne Arjoranta'

paginate:         5
paginate_path:    "/sivu:num/"

# Kokoelmien permalinkit on määritelty käsin, koska
# github-pages hoitaa baseurlit hassusti. Olisi kiva
# jos niihin voisi määritellä {{ site.baseurl }}-
# muuttujan, mutta ilmeisesti sitä ei tueta config-
# tiedostossa. Korjausehdotuksia otetaan vastaan!
collections:
  tyokalut:
    output: true
    permalink: /md-tiede-fi/tyokalut/:path/
  ohjeet:
    output: true
    permalink: /md-tiede-fi/ohjeet/:path/

defaults:
  -
    scope:
      path: ""
      type: "tyokalut" # a collection in your site, in plural form
    values:
      layout: "tyokalu"
  -
    scope:
      path: ""
      type: "ohjeet" # a collection in your site, in plural form
    values:
      layout: "ohje"

# Custom vars
sidebar_image:
version:          

github:
        repo:           https://github.com/gitkrax/md-tiede-fi
