# Dependencies
markdown:         kramdown
highlighter:      rouge

# Gems
gems: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Markdown ja tiede
tagline:          'Ohjeita Markdownin käyttöön tieteeessä'
description:      'Ohjeita Markdown-merkintäkielen käyttöön tieteellisessä työssä'
url:              https://github.com/gitkrax/hyde-fi
baseurl:          ''

author:
  name:           'Jonne Arjoranta'
  url:            https://twitter.com/jaranta

paginate:         5
paginate_path:    "/sivu:num/"

collections:
  tyokalut:
    output: true

# Custom vars
sidebar_image:
version:          0.0.0

github:
  repo:           https://github.com/gitkrax/hyde-fi
